notifications:
  commits: commits@infra.apache.org
  pullrequests: commits@infra.apache.org
  issues: commits@infra.apache.org
  commits_by_path:
    "README.md": humbedooh@apache.org

github:
  description: "Infrastructure Test Repository"
  labels:
    - infrastructure
    - testing  
  protected_branches:
    master:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
